### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by adamltyson** [neuroinformatics-unit/python-cookiecutter#20]
There are lots of things we should test in this repo, but one simple(ish) one is to ensure that the built repository passes it's own linting checks, so we don't have to fix things like #19

**Comment by JoeZiminski** [comment]
I started this in a team coding a while back but didn't look at it since, have created #21 we could use as a basis to discuss / implement these

**Comment by adamltyson** [comment]
[pytest-cookies](https://github.com/hackebrot/pytest-cookies) seems like a handy tool for this.
