### ISSUE TITLE
Add Python 3.11

### ISSUE THREAD

**Issue by dstansby** [neuroinformatics-unit/python-cookiecutter#38]
Python 3.11 has been out for a couple of months now, so it would be good to add configuration for supporting Python 3.11 to the cookiecutter. This needs to happen at least in:
- `tox.ini`
- `pyproject.toml`

But there may be other places, as I haven't looked systematically at this.

**Comment by adamltyson** [comment]
I think it's just there and the actions workflow.

The reason we haven't added it yet is because not all of the main scientific libraries support 3.11 yet. TensorFlow is one that springs to mind, but it may be the last one. Now is probably a good time to update.

**Comment by dstansby** [comment]
`napari` isn't quite there either - this can definitely wait and stay as a placeholder issue until those libraries are working with Python 3.11.

**Comment by niksirbi** [comment]
Maybe now is a good time to do this? Enough time has passed since the 3.11 release

**Comment by adamltyson** [comment]
TensorFlow is on 3.11 now, but napari isn't yet. I'd rather not suggest to users they can use 3.11 when other libraries we recommend aren't yet compatible.

**Comment by adamltyson** [comment]
It is now time.

**Comment by adamltyson** [comment]
And remove 3.8

**Comment by alessandrofelder** [comment]
Reopening, see #88 - will be fixed by #89
