### ISSUE TITLE
[Feature] Cruft json file created within this cookiecutter

### ISSUE THREAD

**Issue by lauraporta** [neuroinformatics-unit/python-cookiecutter#71]
We could add the .cruft.json file and fill it up when the repo is initialised.
It will speed up the use of cruft to update cookiecutter version. We will need to run only `cruft update`. 
Also the commit hash can be retrieved at the moment of dataset creation.

**Comment by adamltyson** [comment]
Closed due to https://github.com/neuroinformatics-unit/python-cookiecutter/issues/47#issuecomment-1792559026
