### ISSUE TITLE
sphinx cannot find extension `sphinx-sitemap`

### ISSUE THREAD

**Issue by ablot** [neuroinformatics-unit/python-cookiecutter#98]
**Describe the bug**
A clear and concise description of what the bug is. If possible, please submit a [Minimal Reproducible Example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

After default install, running `sphinx-build docs/source docs/build` fails because it cannot load `sphinx-sitemap`. 
This was solved by replacing the dash by an underscore in `docs/source/conf.py` in my local project. I assume the fix in the cookiecutter would be the same:
https://github.com/znamlab/python-cookiecutter/commit/56fee90c797a01c252c4f3834a47427eec7a00d4

**To Reproduce**
Please enter full details of how to reproduce this bug.

Create a new project and follow the ReadMe.md:

```
# Install the documentation build dependencies
pip install -r docs/requirements.txt
# Build the documentation
sphinx-build docs/source docs/build
```
or push anything to github (and the action will fail)

**Expected behaviour**

It should run and generate doc

**Log file**
Please attach the log file if relevant.

**Screenshots**
 
Forgot to take one

**Computer used (please complete the following information):**

- OS: both mac and linux

**Additional context**

**Comment by niksirbi** [comment]
Thanks a lot @ablot! You have diagnosed the issue correctly, the `sphinx-sitemap` in `conf.py` should be `sphinx_sitemap`.
We will implement the fix asap.

**Comment by niksirbi** [comment]
Should be fixed now.
